# Model arguments
model_name_or_path: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
output_dir: data/Qwen-7B-Simple-RL
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
use_liger_kernel: true
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false

# Data training arguments
# dataset_name: hoanganhpham/open_r1_sample_easy
dataset_name: open-r1/OpenR1-Math-220k
dataset_configs:
- train
system_prompt: "You are a helpful AI Assistant, designed to provided well-reasoned and detailed responses. You FIRST think about the reasoning process as an internal monologue and then provide the user with the answer. The reasoning process MUST BE enclosed within <think> and </think> tags."

# LORA config
use_peft: true
lora_task_type: CAUSAL_LM
lora_r: 256
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
- q_proj
- v_proj
- k_proj
- o_proj
- gate_proj
- up_proj
- down_proj

warmup_ratio: 0.05
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
num_iterations: 4
num_generations: 4
max_prompt_length: 512
max_completion_length: 8192
per_device_eval_batch_size: 4
per_device_train_batch_size: 4

# GRPO trainer config
temperature: 0.6
bf16: true
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.48
vllm_enable_prefix_caching: true

num_train_epochs: 2

do_eval: true
eval_strategy: steps
eval_steps: 50

save_strategy: steps
save_steps: 50
save_total_limit: 2

log_level: info
logging_strategy: steps
logging_steps: 1

max_steps: -1

push_to_hub: false
hub_model_id: DeepSeek-R1-Distill-Qwen-7B
hub_strategy: every_save

report_to:
- wandb
wandb_entity: andy279
wandb_project: aimo

overwrite_output_dir: true

seed: 42