# Model arguments
wandb_entity: castalk-inc
wandb_project: aimo
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
use_liger_kernel: true

# Data training arguments
num_processes: 4
dataset_name: open-r1/OpenR1-Math-220k
dataset_configs:
- train

use_peft: true
lora_task_type: CAUSAL_LM
lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
- q_proj
- v_proj
- k_proj
- o_proj
- gate_proj
- up_proj
- down_proj

warmup_ratio: 0.05
gradient_accumulation_steps: 2
learning_rate: 1.0e-4
logging_steps: 1
num_generations: 4
max_prompt_length: 512
max_completion_length: 8192
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
model_name_or_path: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
output_dir: data/Qwen-2.5-7B-Simple-RL-2
hub_model_id: DeepSeek-R1-Distill-Qwen-7B
# model_name_or_path: agentica-org/DeepScaleR-1.5B-Preview
# output_dir: data/DeepScaleR-1.5B-Simple-RL-3
# hub_model_id: DeepScaleR-1.5B-Preview
hub_strategy: every_save
num_train_epochs: 3
overwrite_output_dir: true
temperature: 0.6
bf16: true
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.9

# GRPO trainer config
do_eval: true
eval_strategy: steps
eval_steps: 100
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false

log_level: info
logging_strategy: steps
lr_scheduler_type: cosine
max_steps: -1

push_to_hub: false
report_to:
- wandb
save_strategy: steps
save_steps: 100
seed: 42

chat_template: "{% if not add_generation_prompt is defined %}{% set add_generation_prompt = false %}{% endif %}{% set ns = namespace(is_first=false, is_tool=false, is_output_first=true, system_prompt='') %}{%- for message in messages %}{%- if message['role'] == 'system' %}{% set ns.system_prompt = message['content'] %}{%- endif %}{%- endfor %}{{bos_token}}{{ns.system_prompt}}{%- for message in messages %}{%- if message['role'] == 'user' %}{%- set ns.is_tool = false -%}{{'<｜User｜>' + message['content']}}{%- endif %}{%- if message['role'] == 'assistant' and message['content'] is none %}{%- set ns.is_tool = false -%}{%- for tool in message['tool_calls']%}{%- if not ns.is_first %}{{'<｜Assistant｜><｜tool▁calls▁begin｜><｜tool▁call▁begin｜>' + tool['type'] + '<｜tool▁sep｜>' + tool['function']['name'] + '\\n' + '```json' + '\\n' + tool['function']['arguments'] + '\\n' + '```' + '<｜tool▁call▁end｜>'}}{%- set ns.is_first = true -%}{%- else %}{{'\\n' + '<｜tool▁call▁begin｜>' + tool['type'] + '<｜tool▁sep｜>' + tool['function']['name'] + '\\n' + '```json' + '\\n' + tool['function']['arguments'] + '\\n' + '```' + '<｜tool▁call▁end｜>'}}{{'<｜tool▁calls▁end｜><｜end▁of▁sentence｜>'}}{%- endif %}{%- endfor %}{%- endif %}{%- if message['role'] == 'assistant' and message['content'] is not none %}{%- if ns.is_tool %}{{'<｜tool▁outputs▁end｜>' + message['content'] + '<｜end▁of▁sentence｜>'}}{%- set ns.is_tool = false -%}{%- else %}{% set content = message['content'] %}{{'<｜Assistant｜>' + content + '<｜end▁of▁sentence｜>'}}{%- endif %}{%- endif %}{%- if message['role'] == 'tool' %}{%- set ns.is_tool = true -%}{%- if ns.is_output_first %}{{'<｜tool▁outputs▁begin｜><｜tool▁output▁begin｜>' + message['content'] + '<｜tool▁output▁end｜>'}}{%- set ns.is_output_first = false %}{%- else %}{{'\\n<｜tool▁output▁begin｜>' + message['content'] + '<｜tool▁output▁end｜>'}}{%- endif %}{%- endif %}{%- endfor -%}{% if ns.is_tool %}{{'<｜tool▁outputs▁end｜>'}}{% endif %}{% if add_generation_prompt and not ns.is_tool %}{{'<｜Assistant｜>'}}{% endif %}"
